#!/usr/bin/env python3
"""
build_backbone.py — ONE-SHOT refactor.

Reads the monolithic cv/jgrilli_cv.tex and rewrites the five data-backed section
bodies as \input{tex/...} of the auto-generated partials, leaving every other
section (preamble, Vita, Editor, Teaching, Supervision, Grants, Scientific visits,
...) untouched. The original is backed up alongside this script.

Run once:  python3 build_backbone.py
Thereafter the partials are regenerated by generate_cv.py; this script is not
part of the normal build.
"""

import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
CV = os.path.normpath(os.path.join(HERE, "..", "jgrilli_cv.tex"))
BACKUP = os.path.join(HERE, "jgrilli_cv_monolithic_backup.tex")

# section name -> (partial filename, wrapper environment)
TARGETS = {
    "Organized conferences and workshops": ("organized.tex", "outerlist"),
    "Seminars at Institutions":            ("seminars.tex", "outerlist"),
    "Talks at meetings":                   ("meetings.tex", "outerlist"),
    "Publications":                        ("published.tex", "bibenum"),
    "Preprints":                           ("preprint.tex", "bibenum"),
}


def main():
    text = open(CV, encoding="utf-8").read()
    if not os.path.exists(BACKUP):
        with open(BACKUP, "w", encoding="utf-8") as f:
            f.write(text)
        print("Backed up monolith -> %s" % BACKUP)

    # all uncommented top-level section headers, in order
    matches = list(re.finditer(r"(?m)^\\section\{([^}]*)\}", text))

    # rebuild back-to-front so indices stay valid
    for m in reversed(matches):
        name = m.group(1)
        if name not in TARGETS:
            continue
        fname, env = TARGETS[name]
        body_start = m.end()
        # next uncommented section header after this one
        nxt = re.search(r"(?m)^\\section\{", text[body_start:])
        body_end = body_start + nxt.start() if nxt else len(text)
        wrapper = (
            "\n\n\\begin{%s}\n\n\\input{tex/%s}\n\n\\end{%s}\n\n\n"
            % (env, fname, env)
        )
        text = text[:body_start] + wrapper + text[body_end:]
        print("Refactored section: %s -> \\input{tex/%s}" % (name, fname))

    with open(CV, "w", encoding="utf-8") as f:
        f.write(text)
    print("Wrote backbone -> %s" % CV)


if __name__ == "__main__":
    main()
